### ISSUE TITLE
USER STORY: Account registration

### ISSUE THREAD

**Issue by GaborFicsor** [GaborFicsor/steezy-spatula#1]
As a **Site User** I can **register an account** so that **I can comment, and add my own recipes**

**Acceptance Criteria**

- Users should be able to register to the website
- Users should be able to login to the website
- Users should have access to CRUD functionalities only after they have logged in
- Non-registered users should not have access to CRUD functionalities
- The current login state should be reflected to the user

**Tasks**

- [x] Add django-allauth to project
- [x] Create custom templates for register, login and logout
- [x] Add alert messages for register, login and logout
