### ISSUE TITLE
USER STORY: Filter recipes

### ISSUE THREAD

**Issue by GaborFicsor** [GaborFicsor/steezy-spatula#38]
As a **Site User** I can **filter recipes by difficulty, type and keywords** so that I can **easily find recipes that fit my preferences.**

**Acceptance Criteria**

- Users should be able to filter the list of existing recipes with a filter that is easily accessible
- The filter form should be able to combine more selected filters
- Only the filtered results should appear when filtering
- If there are no results, the user should be notified

**Tasks**

- [x] Create a recipe filter form
- [x] Add filter form to RecipeList view
- [x] Render filter form in the recipes template
- [x] The pagination should work with the filtered results
